#define PIN_MCU_SHIFTREGISTER_LATCH 21
#define PIN_MCU_SHIFTREGISTER_DATA 13
#define PIN_MCU_SHIFTREGISTER_CLOCK 5
#define PIN_MCU_ANALOG_BTNS 36
#define PIN_MCU_PULSE_IN1 27
#define PIN_MCU_PULSE_IN2 26
#define PIN_MCU_PULSE_IN3 25
#define PIN_MCU_PULSE_IN4 33
#define PIN_MCU_PULSE_IN5 32
#define PIN_MCU_PULSE_IN6 39
#define PIN_MCU_PULSE_IN7 14
#define PIN_MCU_PULSE_IN8 4


#define NUM_PULSE 8
#define PIN_SR_PULSE_OUT1 15
#define PIN_SR_PULSE_OUT2 14
#define PIN_SR_PULSE_OUT3 13
#define PIN_SR_PULSE_OUT4 12
#define PIN_SR_PULSE_OUT5 11
#define PIN_SR_PULSE_OUT6 10
#define PIN_SR_PULSE_OUT7 9
#define PIN_SR_PULSE_OUT8 8

#define PIN_SR_RELAY1 PIN_SR_PULSE_OUT7
#define PIN_SR_RELAY2 PIN_SR_PULSE_OUT8

#define NUM_LEDS 6
#define PIN_SR_LED1 7
#define PIN_SR_LED2 6
#define PIN_SR_LED3 5
#define PIN_SR_LED4 4
#define PIN_SR_LED5 3
#define PIN_SR_LED6 2


//ANALOG BUTTONS
#define TOLERANCE_ANALOG_BUTTONS_CHANGE 80
#define NUM_BUTTONS 6

#define VAL_ANALOG_BTN1 3150
#define VAL_ANALOG_BTN2 2880
#define VAL_ANALOG_BTN3 2560
#define VAL_ANALOG_BTN4 1820
#define VAL_ANALOG_BTN5 1120
#define VAL_ANALOG_BTN6 820


#define TIME_ANALOG_BUTTON_READ_INTERVAL 200

#define LEN_SHIFT_REGISTER_BITS 16
#define LEN_PIN_CONFIGURATION 12
#define LEN_PIN_INTERRUPTS 8

#define DETACH_ISR 0x00
#define DEFAULT_ISR_MODE DETACH_ISR
#define DEFAULT_PULSE_DEBOUNCE 50
